services:
  db:
    image: postgres:15-alpine
    container_name: db_fastapi
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - .data/postgres:/var/lib/postgresql/data
